// Mock data for development without Supabase
// This data matches the schema.sql seed data

export const mockCategories = [
  // AI & Machine Learning
  { id: '1', name: 'AI & Machine Learning', slug: 'ai-machine-learning', description: 'AI and machine learning tools and platforms', icon: 'Brain', count: 0 },
  { id: '2', name: 'AI Development Platforms', slug: 'ai-development-platforms', description: 'Platforms for developing AI and ML applications', icon: 'Brain', count: 0 },
  { id: '3', name: 'Machine Learning Infrastructure', slug: 'machine-learning-infrastructure', description: 'Infrastructure for training and deploying ML models', icon: 'Server', count: 0 },
  { id: '4', name: 'AI Security & Privacy', slug: 'ai-security-privacy', description: 'Security and privacy tools for AI systems', icon: 'Shield', count: 0 },
  { id: '5', name: 'AI Interaction & Interfaces', slug: 'ai-interaction-interfaces', description: 'Tools for interacting with AI systems', icon: 'MessageCircle', count: 0 },
  
  // Business Software
  { id: '10', name: 'Business Software', slug: 'business-software', description: 'Business and enterprise software', icon: 'Briefcase', count: 0 },
  { id: '11', name: 'CRM & Sales', slug: 'crm-sales', description: 'Customer relationship management and sales tools', icon: 'Users', count: 0 },
  { id: '12', name: 'CRM Systems', slug: 'crm-systems', description: 'Full-featured CRM platforms', icon: 'Users', count: 0 },
  { id: '13', name: 'ERP & Operations', slug: 'erp-operations', description: 'Enterprise resource planning and operations', icon: 'Building', count: 0 },
  { id: '14', name: 'Finance & Accounting', slug: 'finance-accounting', description: 'Financial management and accounting', icon: 'DollarSign', count: 0 },
  { id: '15', name: 'Human Resources (HR)', slug: 'human-resources-hr', description: 'HR management and recruiting', icon: 'UserPlus', count: 0 },
  { id: '16', name: 'Marketing & Customer Engagement', slug: 'marketing-customer-engagement', description: 'Marketing automation and engagement', icon: 'Megaphone', count: 0 },
  { id: '17', name: 'Customer Support & Success', slug: 'customer-support-success', description: 'Customer support management', icon: 'Headphones', count: 0 },
  { id: '18', name: 'E-commerce Platforms', slug: 'e-commerce-platforms', description: 'Online store solutions', icon: 'ShoppingCart', count: 0 },
  { id: '19', name: 'Project & Work Management', slug: 'project-work-management', description: 'Project and team management', icon: 'ClipboardList', count: 0 },
  { id: '20', name: 'Scheduling & Event Management', slug: 'scheduling-event-management', description: 'Scheduling and events', icon: 'Calendar', count: 0 },
  { id: '21', name: 'Collaboration & Communication', slug: 'collaboration-communication', description: 'Team communication tools', icon: 'MessageCircle', count: 0 },
  
  // Content & Publishing
  { id: '25', name: 'Content & Publishing', slug: 'content-publishing', description: 'Content management and publishing', icon: 'FileText', count: 0 },
  { id: '26', name: 'Content Management Systems (CMS)', slug: 'content-management-systems-cms', description: 'Website and content management', icon: 'Globe', count: 0 },
  { id: '27', name: 'Headless CMS', slug: 'headless-cms', description: 'API-first content management', icon: 'Code', count: 0 },
  { id: '28', name: 'Documentation & Knowledge Base', slug: 'documentation-knowledge-base', description: 'Documentation and wiki platforms', icon: 'BookOpen', count: 0 },
  { id: '29', name: 'Learning Management Systems (LMS)', slug: 'learning-management-systems-lms', description: 'E-learning platforms', icon: 'GraduationCap', count: 0 },
  { id: '30', name: 'Publishing Tools', slug: 'publishing-tools', description: 'Digital publishing and blogging', icon: 'Edit', count: 0 },
  { id: '31', name: 'Translation Management', slug: 'translation-management', description: 'Localization and translation', icon: 'Languages', count: 0 },
  
  // Data & Analytics
  { id: '35', name: 'Data & Analytics', slug: 'data-analytics', description: 'Data analysis and business intelligence', icon: 'BarChart3', count: 0 },
  { id: '36', name: 'Analytics', slug: 'analytics', description: 'Web and product analytics', icon: 'TrendingUp', count: 0 },
  { id: '37', name: 'Web Analytics', slug: 'web-analytics', description: 'Website traffic analytics', icon: 'Activity', count: 0 },
  { id: '38', name: 'Product Analytics', slug: 'product-analytics', description: 'Product usage analytics', icon: 'PieChart', count: 0 },
  { id: '39', name: 'Business Intelligence & Reporting', slug: 'business-intelligence-reporting', description: 'BI dashboards and reporting', icon: 'BarChart', count: 0 },
  { id: '40', name: 'Data Visualization', slug: 'data-visualization', description: 'Charts and dashboards', icon: 'LineChart', count: 0 },
  { id: '41', name: 'Data Pipelines & ETL', slug: 'data-pipelines-etl', description: 'ETL and data pipelines', icon: 'GitMerge', count: 0 },
  
  // Developer Tools
  { id: '45', name: 'Developer Tools', slug: 'developer-tools', description: 'Tools for software development', icon: 'Code', count: 0 },
  { id: '46', name: 'IDEs & Code Editors', slug: 'ides-code-editors', description: 'Code editors and IDEs', icon: 'Terminal', count: 0 },
  { id: '47', name: 'API Development & Testing', slug: 'api-development-testing', description: 'API design and testing', icon: 'Plug', count: 0 },
  { id: '48', name: 'API Infrastructure', slug: 'api-infrastructure', description: 'API gateways and management', icon: 'Server', count: 0 },
  { id: '49', name: 'Version Control', slug: 'version-control', description: 'Source code management', icon: 'GitBranch', count: 0 },
  { id: '50', name: 'CI/CD & DevOps', slug: 'cicd-devops', description: 'CI/CD and deployment', icon: 'RefreshCw', count: 0 },
  { id: '51', name: 'Frameworks & Platforms', slug: 'frameworks-platforms', description: 'Development frameworks', icon: 'Layers', count: 0 },
  { id: '52', name: 'Backend as a Service (BaaS)', slug: 'backend-as-a-service-baas', description: 'Backend infrastructure', icon: 'Database', count: 0 },
  { id: '53', name: 'Low-Code & No-Code Platforms', slug: 'low-code-no-code-platforms', description: 'Visual development tools', icon: 'Layout', count: 0 },
  { id: '54', name: 'Website Builders', slug: 'website-builders', description: 'Drag-and-drop website creation', icon: 'PanelsTopLeft', count: 0 },
  { id: '55', name: 'Build & Deployment', slug: 'build-deployment', description: 'Build tools and deployment', icon: 'Package', count: 0 },
  
  // Infrastructure & Operations
  { id: '60', name: 'Infrastructure & Operations', slug: 'infrastructure-operations', description: 'Infrastructure and DevOps', icon: 'Server', count: 0 },
  { id: '61', name: 'Monitoring & Observability', slug: 'monitoring-observability', description: 'System monitoring', icon: 'Activity', count: 0 },
  { id: '62', name: 'Log Management', slug: 'log-management', description: 'Log aggregation and analysis', icon: 'FileText', count: 0 },
  { id: '63', name: 'Error Tracking', slug: 'error-tracking', description: 'Error and exception tracking', icon: 'AlertTriangle', count: 0 },
  { id: '64', name: 'Databases', slug: 'databases', description: 'Database management systems', icon: 'Database', count: 0 },
  { id: '65', name: 'Cloud Infrastructure Management', slug: 'cloud-infrastructure-management', description: 'Cloud resource management', icon: 'Cloud', count: 0 },
  { id: '66', name: 'Infrastructure as Code (IaC)', slug: 'infrastructure-as-code-iac', description: 'Infrastructure provisioning', icon: 'FileCode', count: 0 },
  { id: '67', name: 'Container Orchestration', slug: 'container-orchestration', description: 'Container management', icon: 'Box', count: 0 },
  { id: '68', name: 'Server & VM Management', slug: 'server-vm-management', description: 'Server management', icon: 'HardDrive', count: 0 },
  { id: '69', name: 'Storage Solutions', slug: 'storage-solutions', description: 'Data storage and files', icon: 'HardDrive', count: 0 },
  { id: '70', name: 'Cloud Storage', slug: 'cloud-storage', description: 'Cloud file storage', icon: 'Cloud', count: 0 },
  
  // Security & Privacy
  { id: '75', name: 'Security & Privacy', slug: 'security-privacy', description: 'Security tools and privacy', icon: 'Shield', count: 0 },
  { id: '76', name: 'Identity & Access Management (IAM)', slug: 'identity-access-management-iam', description: 'User auth and authorization', icon: 'Key', count: 0 },
  { id: '77', name: 'Authentication & SSO Providers', slug: 'authentication-sso-providers', description: 'SSO and authentication', icon: 'Lock', count: 0 },
  { id: '78', name: 'Secrets Management', slug: 'secrets-management', description: 'Secure credentials storage', icon: 'KeyRound', count: 0 },
  { id: '79', name: 'Application Security', slug: 'application-security', description: 'Security testing', icon: 'ShieldCheck', count: 0 },
  { id: '80', name: 'Feature Flags', slug: 'feature-flags', description: 'Feature flag management', icon: 'Flag', count: 0 },
  { id: '81', name: 'VPN & Network Security', slug: 'vpn-network-security', description: 'VPN and network security', icon: 'Network', count: 0 },
  { id: '82', name: 'Password Management', slug: 'password-management', description: 'Password managers', icon: 'Lock', count: 0 },
  
  // Productivity & Utilities
  { id: '85', name: 'Productivity & Utilities', slug: 'productivity-utilities', description: 'Productivity tools', icon: 'Zap', count: 0 },
  { id: '86', name: 'Note-Taking & Knowledge Management', slug: 'note-taking-knowledge-management', description: 'Notes and knowledge bases', icon: 'FileText', count: 0 },
  { id: '87', name: 'Time & Task Management', slug: 'time-task-management', description: 'Time and task tracking', icon: 'Clock', count: 0 },
  { id: '88', name: 'Time Tracking', slug: 'time-tracking', description: 'Time logging', icon: 'Timer', count: 0 },
  { id: '89', name: 'Automation Tools', slug: 'automation-tools', description: 'Workflow automation', icon: 'Cog', count: 0 },
  { id: '90', name: 'Workflow Automation Platforms', slug: 'workflow-automation-platforms', description: 'No-code automation', icon: 'GitMerge', count: 0 },
  { id: '91', name: 'Email & Communication', slug: 'email-communication', description: 'Email clients', icon: 'Mail', count: 0 },
  { id: '92', name: 'File Management & Sync', slug: 'file-management-sync', description: 'File organization', icon: 'Folder', count: 0 },
  { id: '93', name: 'Screen Capture & Recording', slug: 'screen-capture-recording', description: 'Screenshot tools', icon: 'Monitor', count: 0 },
  { id: '94', name: 'Personal Finance Management', slug: 'personal-finance-management', description: 'Budgeting apps', icon: 'Wallet', count: 0 },
  
  // Community & Social
  { id: '100', name: 'Community & Social', slug: 'community-social', description: 'Community platforms', icon: 'Users', count: 0 },
  { id: '101', name: 'Community Building Platforms', slug: 'community-building-platforms', description: 'Forums and communities', icon: 'Users', count: 0 },
  { id: '102', name: 'Forum Software', slug: 'forum-software', description: 'Discussion forums', icon: 'MessageSquare', count: 0 },
  
  // Specialized Industries
  { id: '105', name: 'Specialized Industries', slug: 'specialized-industries', description: 'Industry-specific software', icon: 'Building2', count: 0 },
  { id: '106', name: 'Design & Prototyping', slug: 'design-prototyping', description: 'UI/UX design tools', icon: 'Palette', count: 0 },
  { id: '107', name: 'Finance & Fintech', slug: 'finance-fintech', description: 'Financial technology', icon: 'Landmark', count: 0 },
  { id: '108', name: 'Healthcare', slug: 'healthcare', description: 'Healthcare software', icon: 'Heart', count: 0 },
  { id: '109', name: 'Media & Entertainment', slug: 'media-entertainment', description: 'Media production', icon: 'Film', count: 0 },
  { id: '110', name: 'Video Editing', slug: 'video-editing', description: 'Video editing software', icon: 'Video', count: 0 },
  { id: '111', name: 'Audio & Music', slug: 'audio-music', description: 'Audio production', icon: 'Music', count: 0 },
  { id: '112', name: 'Gaming', slug: 'gaming', description: 'Game development', icon: 'Gamepad2', count: 0 },
];

export const mockTechStacks = [
  // Languages
  { id: '1', name: 'JavaScript', slug: 'javascript', website: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', type: 'Language', count: 0 },
  { id: '2', name: 'TypeScript', slug: 'typescript', website: 'https://www.typescriptlang.org', type: 'Language', count: 0 },
  { id: '3', name: 'Python', slug: 'python', website: 'https://www.python.org', type: 'Language', count: 0 },
  { id: '4', name: 'Go', slug: 'go', website: 'https://go.dev', type: 'Language', count: 0 },
  { id: '5', name: 'Rust', slug: 'rust', website: 'https://www.rust-lang.org', type: 'Language', count: 0 },
  { id: '6', name: 'Java', slug: 'java', website: 'https://www.java.com', type: 'Language', count: 0 },
  { id: '7', name: 'PHP', slug: 'php', website: 'https://www.php.net', type: 'Language', count: 0 },
  { id: '8', name: 'Ruby', slug: 'ruby', website: 'https://www.ruby-lang.org', type: 'Language', count: 0 },
  { id: '9', name: 'C#', slug: 'csharp', website: 'https://docs.microsoft.com/en-us/dotnet/csharp/', type: 'Language', count: 0 },
  { id: '10', name: 'Kotlin', slug: 'kotlin', website: 'https://kotlinlang.org', type: 'Language', count: 0 },
  { id: '11', name: 'Swift', slug: 'swift', website: 'https://swift.org', type: 'Language', count: 0 },
  { id: '12', name: 'Elixir', slug: 'elixir', website: 'https://elixir-lang.org', type: 'Language', count: 0 },
  { id: '13', name: 'Scala', slug: 'scala', website: 'https://www.scala-lang.org', type: 'Language', count: 0 },
  { id: '14', name: 'Clojure', slug: 'clojure', website: 'https://clojure.org', type: 'Language', count: 0 },
  { id: '15', name: 'Zig', slug: 'zig', website: 'https://ziglang.org', type: 'Language', count: 0 },
  
  // Frontend Frameworks
  { id: '20', name: 'React', slug: 'react', website: 'https://react.dev', type: 'Framework', count: 0 },
  { id: '21', name: 'Vue.js', slug: 'vuejs', website: 'https://vuejs.org', type: 'Framework', count: 0 },
  { id: '22', name: 'Svelte', slug: 'svelte', website: 'https://svelte.dev', type: 'Framework', count: 0 },
  { id: '23', name: 'Angular', slug: 'angular', website: 'https://angular.io', type: 'Framework', count: 0 },
  { id: '24', name: 'Next.js', slug: 'nextjs', website: 'https://nextjs.org', type: 'Framework', count: 0 },
  { id: '25', name: 'Nuxt', slug: 'nuxt', website: 'https://nuxt.com', type: 'Framework', count: 0 },
  { id: '26', name: 'Remix', slug: 'remix', website: 'https://remix.run', type: 'Framework', count: 0 },
  { id: '27', name: 'Astro', slug: 'astro', website: 'https://astro.build', type: 'Framework', count: 0 },
  { id: '28', name: 'SvelteKit', slug: 'sveltekit', website: 'https://kit.svelte.dev', type: 'Framework', count: 0 },
  { id: '29', name: 'Solid.js', slug: 'solidjs', website: 'https://www.solidjs.com', type: 'Framework', count: 0 },
  { id: '30', name: 'Qwik', slug: 'qwik', website: 'https://qwik.builder.io', type: 'Framework', count: 0 },
  { id: '31', name: 'Preact', slug: 'preact', website: 'https://preactjs.com', type: 'Framework', count: 0 },
  { id: '32', name: 'Ember.js', slug: 'emberjs', website: 'https://emberjs.com', type: 'Framework', count: 0 },
  { id: '33', name: 'Alpine.js', slug: 'alpinejs', website: 'https://alpinejs.dev', type: 'Framework', count: 0 },
  { id: '34', name: 'HTMX', slug: 'htmx', website: 'https://htmx.org', type: 'Framework', count: 0 },
  
  // Backend Frameworks
  { id: '40', name: 'Node.js', slug: 'nodejs', website: 'https://nodejs.org', type: 'Framework', count: 0 },
  { id: '41', name: 'Express', slug: 'express', website: 'https://expressjs.com', type: 'Framework', count: 0 },
  { id: '42', name: 'Fastify', slug: 'fastify', website: 'https://fastify.dev', type: 'Framework', count: 0 },
  { id: '43', name: 'NestJS', slug: 'nestjs', website: 'https://nestjs.com', type: 'Framework', count: 0 },
  { id: '44', name: 'Django', slug: 'django', website: 'https://www.djangoproject.com', type: 'Framework', count: 0 },
  { id: '45', name: 'FastAPI', slug: 'fastapi', website: 'https://fastapi.tiangolo.com', type: 'Framework', count: 0 },
  { id: '46', name: 'Flask', slug: 'flask', website: 'https://flask.palletsprojects.com', type: 'Framework', count: 0 },
  { id: '47', name: 'Rails', slug: 'rails', website: 'https://rubyonrails.org', type: 'Framework', count: 0 },
  { id: '48', name: 'Laravel', slug: 'laravel', website: 'https://laravel.com', type: 'Framework', count: 0 },
  { id: '49', name: 'Spring Boot', slug: 'spring-boot', website: 'https://spring.io/projects/spring-boot', type: 'Framework', count: 0 },
  { id: '50', name: 'Phoenix', slug: 'phoenix', website: 'https://www.phoenixframework.org', type: 'Framework', count: 0 },
  { id: '51', name: 'Gin', slug: 'gin', website: 'https://gin-gonic.com', type: 'Framework', count: 0 },
  { id: '52', name: 'Fiber', slug: 'fiber', website: 'https://gofiber.io', type: 'Framework', count: 0 },
  { id: '53', name: 'Actix', slug: 'actix', website: 'https://actix.rs', type: 'Framework', count: 0 },
  { id: '54', name: 'Hono', slug: 'hono', website: 'https://hono.dev', type: 'Framework', count: 0 },
  { id: '55', name: 'Elysia', slug: 'elysia', website: 'https://elysiajs.com', type: 'Framework', count: 0 },
  
  // Mobile
  { id: '60', name: 'React Native', slug: 'react-native', website: 'https://reactnative.dev', type: 'Framework', count: 0 },
  { id: '61', name: 'Flutter', slug: 'flutter', website: 'https://flutter.dev', type: 'Framework', count: 0 },
  { id: '62', name: 'Expo', slug: 'expo', website: 'https://expo.dev', type: 'Framework', count: 0 },
  { id: '63', name: 'Ionic', slug: 'ionic', website: 'https://ionicframework.com', type: 'Framework', count: 0 },
  { id: '64', name: 'Capacitor', slug: 'capacitor', website: 'https://capacitorjs.com', type: 'Framework', count: 0 },
  { id: '65', name: 'Tauri', slug: 'tauri', website: 'https://tauri.app', type: 'Framework', count: 0 },
  { id: '66', name: 'Electron', slug: 'electron', website: 'https://www.electronjs.org', type: 'Framework', count: 0 },
  
  // Databases
  { id: '70', name: 'PostgreSQL', slug: 'postgresql', website: 'https://www.postgresql.org', type: 'DB', count: 0 },
  { id: '71', name: 'MySQL', slug: 'mysql', website: 'https://www.mysql.com', type: 'DB', count: 0 },
  { id: '72', name: 'MongoDB', slug: 'mongodb', website: 'https://www.mongodb.com', type: 'DB', count: 0 },
  { id: '73', name: 'Redis', slug: 'redis', website: 'https://redis.io', type: 'DB', count: 0 },
  { id: '74', name: 'SQLite', slug: 'sqlite', website: 'https://www.sqlite.org', type: 'DB', count: 0 },
  { id: '75', name: 'MariaDB', slug: 'mariadb', website: 'https://mariadb.org', type: 'DB', count: 0 },
  { id: '76', name: 'Cassandra', slug: 'cassandra', website: 'https://cassandra.apache.org', type: 'DB', count: 0 },
  { id: '77', name: 'Elasticsearch', slug: 'elasticsearch', website: 'https://www.elastic.co/elasticsearch', type: 'DB', count: 0 },
  { id: '78', name: 'CockroachDB', slug: 'cockroachdb', website: 'https://www.cockroachlabs.com', type: 'DB', count: 0 },
  { id: '79', name: 'PlanetScale', slug: 'planetscale', website: 'https://planetscale.com', type: 'DB', count: 0 },
  { id: '80', name: 'Supabase', slug: 'supabase', website: 'https://supabase.com', type: 'DB', count: 0 },
  { id: '81', name: 'Firebase', slug: 'firebase', website: 'https://firebase.google.com', type: 'DB', count: 0 },
  { id: '82', name: 'Prisma', slug: 'prisma', website: 'https://www.prisma.io', type: 'DB', count: 0 },
  { id: '83', name: 'Drizzle', slug: 'drizzle', website: 'https://orm.drizzle.team', type: 'DB', count: 0 },
  { id: '84', name: 'Turso', slug: 'turso', website: 'https://turso.tech', type: 'DB', count: 0 },
  { id: '85', name: 'Neon', slug: 'neon', website: 'https://neon.tech', type: 'DB', count: 0 },
  { id: '86', name: 'DynamoDB', slug: 'dynamodb', website: 'https://aws.amazon.com/dynamodb', type: 'DB', count: 0 },
  { id: '87', name: 'ClickHouse', slug: 'clickhouse', website: 'https://clickhouse.com', type: 'DB', count: 0 },
  { id: '88', name: 'TimescaleDB', slug: 'timescaledb', website: 'https://www.timescale.com', type: 'DB', count: 0 },
  { id: '89', name: 'InfluxDB', slug: 'influxdb', website: 'https://www.influxdata.com', type: 'DB', count: 0 },
  
  // Cloud & Hosting
  { id: '100', name: 'AWS', slug: 'aws', website: 'https://aws.amazon.com', type: 'Cloud', count: 0 },
  { id: '101', name: 'Google Cloud', slug: 'google-cloud', website: 'https://cloud.google.com', type: 'Cloud', count: 0 },
  { id: '102', name: 'Azure', slug: 'azure', website: 'https://azure.microsoft.com', type: 'Cloud', count: 0 },
  { id: '103', name: 'Vercel', slug: 'vercel', website: 'https://vercel.com', type: 'Hosting', count: 0 },
  { id: '104', name: 'Netlify', slug: 'netlify', website: 'https://www.netlify.com', type: 'Hosting', count: 0 },
  { id: '105', name: 'Cloudflare', slug: 'cloudflare', website: 'https://www.cloudflare.com', type: 'Hosting', count: 0 },
  { id: '106', name: 'Railway', slug: 'railway', website: 'https://railway.app', type: 'Hosting', count: 0 },
  { id: '107', name: 'Render', slug: 'render', website: 'https://render.com', type: 'Hosting', count: 0 },
  { id: '108', name: 'Fly.io', slug: 'flyio', website: 'https://fly.io', type: 'Hosting', count: 0 },
  { id: '109', name: 'DigitalOcean', slug: 'digitalocean', website: 'https://www.digitalocean.com', type: 'Cloud', count: 0 },
  { id: '110', name: 'Linode', slug: 'linode', website: 'https://www.linode.com', type: 'Cloud', count: 0 },
  { id: '111', name: 'Hetzner', slug: 'hetzner', website: 'https://www.hetzner.com', type: 'Cloud', count: 0 },
  { id: '112', name: 'Heroku', slug: 'heroku', website: 'https://www.heroku.com', type: 'Hosting', count: 0 },
  
  // DevOps & CI/CD
  { id: '120', name: 'Docker', slug: 'docker', website: 'https://www.docker.com', type: 'Tool', count: 0 },
  { id: '121', name: 'Kubernetes', slug: 'kubernetes', website: 'https://kubernetes.io', type: 'Tool', count: 0 },
  { id: '122', name: 'GitHub Actions', slug: 'github-actions', website: 'https://github.com/features/actions', type: 'CI', count: 0 },
  { id: '123', name: 'GitLab CI', slug: 'gitlab-ci', website: 'https://docs.gitlab.com/ee/ci/', type: 'CI', count: 0 },
  { id: '124', name: 'Jenkins', slug: 'jenkins', website: 'https://www.jenkins.io', type: 'CI', count: 0 },
  { id: '125', name: 'CircleCI', slug: 'circleci', website: 'https://circleci.com', type: 'CI', count: 0 },
  { id: '126', name: 'Travis CI', slug: 'travis-ci', website: 'https://www.travis-ci.com', type: 'CI', count: 0 },
  { id: '127', name: 'Terraform', slug: 'terraform', website: 'https://www.terraform.io', type: 'Tool', count: 0 },
  { id: '128', name: 'Pulumi', slug: 'pulumi', website: 'https://www.pulumi.com', type: 'Tool', count: 0 },
  { id: '129', name: 'Ansible', slug: 'ansible', website: 'https://www.ansible.com', type: 'Tool', count: 0 },
  { id: '130', name: 'Helm', slug: 'helm', website: 'https://helm.sh', type: 'Tool', count: 0 },
  
  // Monitoring & Analytics
  { id: '140', name: 'Prometheus', slug: 'prometheus', website: 'https://prometheus.io', type: 'Monitoring', count: 0 },
  { id: '141', name: 'Grafana', slug: 'grafana', website: 'https://grafana.com', type: 'Monitoring', count: 0 },
  { id: '142', name: 'Datadog', slug: 'datadog', website: 'https://www.datadoghq.com', type: 'Monitoring', count: 0 },
  { id: '143', name: 'New Relic', slug: 'new-relic', website: 'https://newrelic.com', type: 'Monitoring', count: 0 },
  { id: '144', name: 'Sentry', slug: 'sentry', website: 'https://sentry.io', type: 'Monitoring', count: 0 },
  { id: '145', name: 'Plausible', slug: 'plausible', website: 'https://plausible.io', type: 'Analytics', count: 0 },
  { id: '146', name: 'PostHog', slug: 'posthog', website: 'https://posthog.com', type: 'Analytics', count: 0 },
  { id: '147', name: 'Mixpanel', slug: 'mixpanel', website: 'https://mixpanel.com', type: 'Analytics', count: 0 },
  { id: '148', name: 'Amplitude', slug: 'amplitude', website: 'https://amplitude.com', type: 'Analytics', count: 0 },
  { id: '149', name: 'OpenTelemetry', slug: 'opentelemetry', website: 'https://opentelemetry.io', type: 'Monitoring', count: 0 },
  { id: '150', name: 'Jaeger', slug: 'jaeger', website: 'https://www.jaegertracing.io', type: 'Monitoring', count: 0 },
  
  // Auth & Security
  { id: '160', name: 'Auth0', slug: 'auth0', website: 'https://auth0.com', type: 'SaaS', count: 0 },
  { id: '161', name: 'Clerk', slug: 'clerk', website: 'https://clerk.com', type: 'SaaS', count: 0 },
  { id: '162', name: 'NextAuth.js', slug: 'nextauthjs', website: 'https://next-auth.js.org', type: 'Tool', count: 0 },
  { id: '163', name: 'Keycloak', slug: 'keycloak', website: 'https://www.keycloak.org', type: 'Tool', count: 0 },
  { id: '164', name: 'Ory', slug: 'ory', website: 'https://www.ory.sh', type: 'Tool', count: 0 },
  { id: '165', name: 'Lucia', slug: 'lucia', website: 'https://lucia-auth.com', type: 'Tool', count: 0 },
  { id: '166', name: 'Passport.js', slug: 'passportjs', website: 'https://www.passportjs.org', type: 'Tool', count: 0 },
  
  // Messaging & Queues
  { id: '170', name: 'RabbitMQ', slug: 'rabbitmq', website: 'https://www.rabbitmq.com', type: 'Messaging', count: 0 },
  { id: '171', name: 'Kafka', slug: 'kafka', website: 'https://kafka.apache.org', type: 'Messaging', count: 0 },
  { id: '172', name: 'NATS', slug: 'nats', website: 'https://nats.io', type: 'Messaging', count: 0 },
  { id: '173', name: 'BullMQ', slug: 'bullmq', website: 'https://bullmq.io', type: 'Messaging', count: 0 },
  { id: '174', name: 'Celery', slug: 'celery', website: 'https://docs.celeryq.dev', type: 'Messaging', count: 0 },
  { id: '175', name: 'Temporal', slug: 'temporal', website: 'https://temporal.io', type: 'Messaging', count: 0 },
  
  // Storage
  { id: '180', name: 'S3', slug: 's3', website: 'https://aws.amazon.com/s3', type: 'Storage', count: 0 },
  { id: '181', name: 'Cloudflare R2', slug: 'cloudflare-r2', website: 'https://www.cloudflare.com/products/r2', type: 'Storage', count: 0 },
  { id: '182', name: 'MinIO', slug: 'minio', website: 'https://min.io', type: 'Storage', count: 0 },
  { id: '183', name: 'Uploadthing', slug: 'uploadthing', website: 'https://uploadthing.com', type: 'Storage', count: 0 },
  
  // APIs & Protocols
  { id: '190', name: 'GraphQL', slug: 'graphql', website: 'https://graphql.org', type: 'API', count: 0 },
  { id: '191', name: 'tRPC', slug: 'trpc', website: 'https://trpc.io', type: 'API', count: 0 },
  { id: '192', name: 'gRPC', slug: 'grpc', website: 'https://grpc.io', type: 'API', count: 0 },
  { id: '193', name: 'REST', slug: 'rest', website: 'https://restfulapi.net', type: 'API', count: 0 },
  { id: '194', name: 'WebSockets', slug: 'websockets', website: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API', type: 'API', count: 0 },
  { id: '195', name: 'Socket.io', slug: 'socketio', website: 'https://socket.io', type: 'API', count: 0 },
  
  // Testing
  { id: '200', name: 'Jest', slug: 'jest', website: 'https://jestjs.io', type: 'Tool', count: 0 },
  { id: '201', name: 'Vitest', slug: 'vitest', website: 'https://vitest.dev', type: 'Tool', count: 0 },
  { id: '202', name: 'Playwright', slug: 'playwright', website: 'https://playwright.dev', type: 'Tool', count: 0 },
  { id: '203', name: 'Cypress', slug: 'cypress', website: 'https://www.cypress.io', type: 'Tool', count: 0 },
  { id: '204', name: 'Selenium', slug: 'selenium', website: 'https://www.selenium.dev', type: 'Tool', count: 0 },
  { id: '205', name: 'Testing Library', slug: 'testing-library', website: 'https://testing-library.com', type: 'Tool', count: 0 },
  { id: '206', name: 'Pytest', slug: 'pytest', website: 'https://pytest.org', type: 'Tool', count: 0 },
  
  // Build Tools
  { id: '210', name: 'Vite', slug: 'vite', website: 'https://vitejs.dev', type: 'Tool', count: 0 },
  { id: '211', name: 'Webpack', slug: 'webpack', website: 'https://webpack.js.org', type: 'Tool', count: 0 },
  { id: '212', name: 'esbuild', slug: 'esbuild', website: 'https://esbuild.github.io', type: 'Tool', count: 0 },
  { id: '213', name: 'Turbopack', slug: 'turbopack', website: 'https://turbo.build/pack', type: 'Tool', count: 0 },
  { id: '214', name: 'Turborepo', slug: 'turborepo', website: 'https://turbo.build/repo', type: 'Tool', count: 0 },
  { id: '215', name: 'pnpm', slug: 'pnpm', website: 'https://pnpm.io', type: 'Tool', count: 0 },
  { id: '216', name: 'Bun', slug: 'bun', website: 'https://bun.sh', type: 'Tool', count: 0 },
  
  // CMS & Headless
  { id: '220', name: 'Strapi', slug: 'strapi', website: 'https://strapi.io', type: 'App', count: 0 },
  { id: '221', name: 'Sanity', slug: 'sanity', website: 'https://www.sanity.io', type: 'SaaS', count: 0 },
  { id: '222', name: 'Contentful', slug: 'contentful', website: 'https://www.contentful.com', type: 'SaaS', count: 0 },
  { id: '223', name: 'Payload', slug: 'payload', website: 'https://payloadcms.com', type: 'App', count: 0 },
  { id: '224', name: 'Ghost', slug: 'ghost', website: 'https://ghost.org', type: 'App', count: 0 },
  { id: '225', name: 'WordPress', slug: 'wordpress', website: 'https://wordpress.org', type: 'App', count: 0 },
  { id: '226', name: 'Directus', slug: 'directus', website: 'https://directus.io', type: 'App', count: 0 },
  
  // AI & ML
  { id: '230', name: 'OpenAI', slug: 'openai', website: 'https://openai.com', type: 'SaaS', count: 0 },
  { id: '231', name: 'Anthropic', slug: 'anthropic', website: 'https://www.anthropic.com', type: 'SaaS', count: 0 },
  { id: '232', name: 'Hugging Face', slug: 'huggingface', website: 'https://huggingface.co', type: 'SaaS', count: 0 },
  { id: '233', name: 'LangChain', slug: 'langchain', website: 'https://www.langchain.com', type: 'Tool', count: 0 },
  { id: '234', name: 'Ollama', slug: 'ollama', website: 'https://ollama.ai', type: 'Tool', count: 0 },
  { id: '235', name: 'Pinecone', slug: 'pinecone', website: 'https://www.pinecone.io', type: 'DB', count: 0 },
  { id: '236', name: 'Weaviate', slug: 'weaviate', website: 'https://weaviate.io', type: 'DB', count: 0 },
  { id: '237', name: 'Milvus', slug: 'milvus', website: 'https://milvus.io', type: 'DB', count: 0 },
  { id: '238', name: 'Chroma', slug: 'chroma', website: 'https://www.trychroma.com', type: 'DB', count: 0 },
  { id: '239', name: 'Replicate', slug: 'replicate', website: 'https://replicate.com', type: 'SaaS', count: 0 },
  { id: '240', name: 'Vercel AI SDK', slug: 'vercel-ai', website: 'https://sdk.vercel.ai', type: 'Tool', count: 0 },
  
  // Search
  { id: '250', name: 'Algolia', slug: 'algolia', website: 'https://www.algolia.com', type: 'SaaS', count: 0 },
  { id: '251', name: 'Meilisearch', slug: 'meilisearch', website: 'https://www.meilisearch.com', type: 'Tool', count: 0 },
  { id: '252', name: 'Typesense', slug: 'typesense', website: 'https://typesense.org', type: 'Tool', count: 0 },
  
  // UI Libraries
  { id: '260', name: 'Tailwind CSS', slug: 'tailwindcss', website: 'https://tailwindcss.com', type: 'Tool', count: 0 },
  { id: '261', name: 'shadcn/ui', slug: 'shadcn-ui', website: 'https://ui.shadcn.com', type: 'Tool', count: 0 },
  { id: '262', name: 'Radix UI', slug: 'radix-ui', website: 'https://www.radix-ui.com', type: 'Tool', count: 0 },
  { id: '263', name: 'Chakra UI', slug: 'chakra-ui', website: 'https://chakra-ui.com', type: 'Tool', count: 0 },
  { id: '264', name: 'Material UI', slug: 'material-ui', website: 'https://mui.com', type: 'Tool', count: 0 },
  { id: '265', name: 'Ant Design', slug: 'ant-design', website: 'https://ant.design', type: 'Tool', count: 0 },
  { id: '266', name: 'Mantine', slug: 'mantine', website: 'https://mantine.dev', type: 'Tool', count: 0 },
];

export const mockAlternatives = [
  {
    id: '1',
    name: 'VS Code',
    slug: 'vs-code',
    short_description: 'A free, open-source code editor with excellent extension support.',
    description: 'A free, open-source code editor with excellent extension support.',
    website: 'https://code.visualstudio.com',
    github: 'https://github.com/microsoft/vscode',
    icon_url: null,
    stars: 158000,
    forks: 27800,
    license: 'MIT',
    health_score: 95,
    is_self_hosted: false,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '46', name: 'IDEs & Code Editors', slug: 'ides-code-editors' }],
    tags: [{ id: '1', name: 'editor', slug: 'editor' }],
    techStacks: [
      { id: '2', name: 'TypeScript', slug: 'typescript', type: 'Language' },
      { id: '66', name: 'Electron', slug: 'electron', type: 'Framework' },
    ],
    proprietarySoftware: [{ id: '1', name: 'Sublime Text', slug: 'sublime-text' }],
  },
  {
    id: '2',
    name: 'Supabase',
    slug: 'supabase',
    short_description: 'The open source Firebase alternative with Postgres database.',
    description: 'The open source Firebase alternative with Postgres database.',
    website: 'https://supabase.com',
    github: 'https://github.com/supabase/supabase',
    icon_url: null,
    stars: 63000,
    forks: 5800,
    license: 'Apache-2.0',
    health_score: 92,
    is_self_hosted: true,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '52', name: 'Backend as a Service (BaaS)', slug: 'backend-as-a-service-baas' }],
    tags: [{ id: '2', name: 'database', slug: 'database' }],
    techStacks: [
      { id: '2', name: 'TypeScript', slug: 'typescript', type: 'Language' },
      { id: '70', name: 'PostgreSQL', slug: 'postgresql', type: 'DB' },
    ],
    proprietarySoftware: [{ id: '2', name: 'Firebase', slug: 'firebase' }],
  },
  {
    id: '3',
    name: 'Plausible Analytics',
    slug: 'plausible-analytics',
    short_description: 'Simple, privacy-friendly Google Analytics alternative.',
    description: 'Simple, privacy-friendly Google Analytics alternative.',
    website: 'https://plausible.io',
    github: 'https://github.com/plausible/analytics',
    icon_url: null,
    stars: 18000,
    forks: 970,
    license: 'AGPL-3.0',
    health_score: 88,
    is_self_hosted: true,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '37', name: 'Web Analytics', slug: 'web-analytics' }],
    tags: [{ id: '3', name: 'analytics', slug: 'analytics' }],
    techStacks: [
      { id: '12', name: 'Elixir', slug: 'elixir', type: 'Language' },
      { id: '50', name: 'Phoenix', slug: 'phoenix', type: 'Framework' },
    ],
    proprietarySoftware: [{ id: '3', name: 'Google Analytics', slug: 'google-analytics' }],
  },
  {
    id: '4',
    name: 'GIMP',
    slug: 'gimp',
    short_description: 'Free and open source image editor.',
    description: 'GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows and more. It is free software, you can change its source code and distribute your changes.',
    website: 'https://www.gimp.org',
    github: 'https://github.com/GNOME/gimp',
    icon_url: null,
    stars: 4500,
    forks: 800,
    license: 'GPL-3.0',
    health_score: 85,
    is_self_hosted: false,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '106', name: 'Design & Prototyping', slug: 'design-prototyping' }],
    tags: [{ id: '5', name: 'image-editing', slug: 'image-editing' }],
    techStacks: [
      { id: '16', name: 'C', slug: 'c', type: 'Language' },
    ],
    proprietarySoftware: [{ id: '9', name: 'Photoshop', slug: 'photoshop' }],
  },
  {
    id: '5',
    name: 'Mattermost',
    slug: 'mattermost',
    short_description: 'Open source platform for secure team collaboration.',
    description: 'Mattermost is an open source platform for secure collaboration across the entire software development lifecycle.',
    website: 'https://mattermost.com',
    github: 'https://github.com/mattermost/mattermost-server',
    icon_url: null,
    stars: 28000,
    forks: 6900,
    license: 'MIT',
    health_score: 90,
    is_self_hosted: true,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '21', name: 'Collaboration & Communication', slug: 'collaboration-communication' }],
    tags: [{ id: '6', name: 'chat', slug: 'chat' }],
    techStacks: [
      { id: '4', name: 'Go', slug: 'go', type: 'Language' },
      { id: '20', name: 'React', slug: 'react', type: 'Framework' },
    ],
    proprietarySoftware: [{ id: '4', name: 'Slack', slug: 'slack' }],
  },
  {
    id: '6',
    name: 'Outline',
    slug: 'outline',
    short_description: 'The fastest knowledge base for growing teams.',
    description: 'A fast, collaborative, knowledge base for your team built with React and Node.js.',
    website: 'https://www.getoutline.com',
    github: 'https://github.com/outline/outline',
    icon_url: null,
    stars: 23000,
    forks: 2000,
    license: 'BSD-3-Clause',
    health_score: 87,
    is_self_hosted: true,
    approved: true,
    featured: false,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '86', name: 'Note-Taking & Knowledge Management', slug: 'note-taking-knowledge-management' }],
    tags: [{ id: '7', name: 'documentation', slug: 'documentation' }],
    techStacks: [
      { id: '2', name: 'TypeScript', slug: 'typescript', type: 'Language' },
      { id: '20', name: 'React', slug: 'react', type: 'Framework' },
    ],
    proprietarySoftware: [{ id: '5', name: 'Notion', slug: 'notion' }],
  },
  {
    id: '7',
    name: 'Penpot',
    slug: 'penpot',
    short_description: 'Open source design and prototyping platform.',
    description: 'Penpot is the first open-source design and prototyping platform meant for cross-domain teams.',
    website: 'https://penpot.app',
    github: 'https://github.com/penpot/penpot',
    icon_url: null,
    stars: 26000,
    forks: 1200,
    license: 'MPL-2.0',
    health_score: 89,
    is_self_hosted: true,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '106', name: 'Design & Prototyping', slug: 'design-prototyping' }],
    tags: [{ id: '8', name: 'design', slug: 'design' }],
    techStacks: [
      { id: '14', name: 'Clojure', slug: 'clojure', type: 'Language' },
    ],
    proprietarySoftware: [{ id: '6', name: 'Figma', slug: 'figma' }],
  },
  {
    id: '8',
    name: 'Jitsi Meet',
    slug: 'jitsi-meet',
    short_description: 'Secure, simple and scalable video conferencing.',
    description: 'Jitsi Meet is a fully encrypted, 100% open source video conferencing solution.',
    website: 'https://jitsi.org/jitsi-meet/',
    github: 'https://github.com/jitsi/jitsi-meet',
    icon_url: null,
    stars: 21000,
    forks: 6500,
    license: 'Apache-2.0',
    health_score: 86,
    is_self_hosted: true,
    approved: true,
    featured: false,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '21', name: 'Collaboration & Communication', slug: 'collaboration-communication' }],
    tags: [{ id: '9', name: 'video-conferencing', slug: 'video-conferencing' }],
    techStacks: [
      { id: '1', name: 'JavaScript', slug: 'javascript', type: 'Language' },
      { id: '20', name: 'React', slug: 'react', type: 'Framework' },
    ],
    proprietarySoftware: [{ id: '13', name: 'Zoom', slug: 'zoom' }],
  },
  {
    id: '9',
    name: 'Nextcloud',
    slug: 'nextcloud',
    short_description: 'Self-hosted productivity platform and file sync.',
    description: 'A safe home for all your data. Access & share your files, calendars, contacts, mail & more.',
    website: 'https://nextcloud.com',
    github: 'https://github.com/nextcloud/server',
    icon_url: null,
    stars: 25000,
    forks: 3800,
    license: 'AGPL-3.0',
    health_score: 91,
    is_self_hosted: true,
    approved: true,
    featured: true,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '70', name: 'Cloud Storage', slug: 'cloud-storage' }],
    tags: [{ id: '10', name: 'file-sync', slug: 'file-sync' }],
    techStacks: [
      { id: '7', name: 'PHP', slug: 'php', type: 'Language' },
    ],
    proprietarySoftware: [{ id: '11', name: 'Dropbox', slug: 'dropbox' }],
  },
  {
    id: '10',
    name: 'LibreOffice',
    slug: 'libreoffice',
    short_description: 'Free and powerful office suite.',
    description: 'LibreOffice is a free and powerful office suite, and a successor to OpenOffice.org.',
    website: 'https://www.libreoffice.org',
    github: 'https://github.com/LibreOffice/core',
    icon_url: null,
    stars: 2000,
    forks: 600,
    license: 'MPL-2.0',
    health_score: 88,
    is_self_hosted: false,
    approved: true,
    featured: false,
    submitter_name: null,
    submitter_email: null,
    screenshots: null,
    categories: [{ id: '85', name: 'Productivity & Utilities', slug: 'productivity-utilities' }],
    tags: [{ id: '11', name: 'office', slug: 'office' }],
    techStacks: [
      { id: '17', name: 'C++', slug: 'cpp', type: 'Language' },
    ],
    proprietarySoftware: [{ id: '10', name: 'Microsoft Office', slug: 'microsoft-office' }],
  },
];

export const mockProprietary = [
  { id: '1', name: 'Sublime Text', slug: 'sublime-text', description: 'Proprietary code editor', website: 'https://www.sublimetext.com', count: 1 },
  { id: '2', name: 'Firebase', slug: 'firebase', description: 'Google\'s app development platform', website: 'https://firebase.google.com', count: 1 },
  { id: '3', name: 'Google Analytics', slug: 'google-analytics', description: 'Web analytics service', website: 'https://analytics.google.com', count: 1 },
  { id: '4', name: 'Slack', slug: 'slack', description: 'Team messaging platform', website: 'https://slack.com', count: 0 },
  { id: '5', name: 'Notion', slug: 'notion', description: 'All-in-one workspace', website: 'https://notion.so', count: 0 },
  { id: '6', name: 'Figma', slug: 'figma', description: 'Design tool', website: 'https://figma.com', count: 0 },
  { id: '7', name: 'GitHub Copilot', slug: 'github-copilot', description: 'AI pair programmer', website: 'https://github.com/features/copilot', count: 0 },
  { id: '8', name: 'Jira', slug: 'jira', description: 'Project management', website: 'https://www.atlassian.com/software/jira', count: 0 },
  { id: '9', name: 'Photoshop', slug: 'photoshop', description: 'Image editing software', website: 'https://www.adobe.com/products/photoshop.html', count: 0 },
  { id: '10', name: 'Microsoft Office', slug: 'microsoft-office', description: 'Office productivity suite', website: 'https://www.microsoft.com/microsoft-365', count: 0 },
  { id: '11', name: 'Dropbox', slug: 'dropbox', description: 'Cloud storage service', website: 'https://www.dropbox.com', count: 0 },
  { id: '12', name: 'Trello', slug: 'trello', description: 'Project management board', website: 'https://trello.com', count: 0 },
  { id: '13', name: 'Zoom', slug: 'zoom', description: 'Video conferencing', website: 'https://zoom.us', count: 0 },
  { id: '14', name: 'Adobe Premiere', slug: 'adobe-premiere', description: 'Video editing software', website: 'https://www.adobe.com/products/premiere.html', count: 0 },
  { id: '15', name: 'Adobe Illustrator', slug: 'adobe-illustrator', description: 'Vector graphics editor', website: 'https://www.adobe.com/products/illustrator.html', count: 0 },
  { id: '16', name: 'Mailchimp', slug: 'mailchimp', description: 'Email marketing platform', website: 'https://mailchimp.com', count: 0 },
  { id: '17', name: 'Intercom', slug: 'intercom', description: 'Customer messaging platform', website: 'https://www.intercom.com', count: 0 },
  { id: '18', name: 'Zendesk', slug: 'zendesk', description: 'Customer service software', website: 'https://www.zendesk.com', count: 0 },
  { id: '19', name: 'Airtable', slug: 'airtable', description: 'Spreadsheet-database hybrid', website: 'https://airtable.com', count: 0 },
  { id: '20', name: 'Monday.com', slug: 'monday-com', description: 'Work management platform', website: 'https://monday.com', count: 0 },
];

export const mockTags = [
  { id: '1', name: 'editor', slug: 'editor', count: 1 },
  { id: '2', name: 'database', slug: 'database', count: 1 },
  { id: '3', name: 'analytics', slug: 'analytics', count: 1 },
  { id: '4', name: 'self-hosted', slug: 'self-hosted', count: 2 },
  { id: '5', name: 'privacy', slug: 'privacy', count: 1 },
];
